### ISSUE TITLE
publishing to npmjs.com

### ISSUE THREAD

**Issue by stackmagic** [evshiron/node-flow#2]
So what are the chances of this being published to npmjs as well? There's already an ancient package on npmjs under the same name. I just tried finding an alternative name but every short-ish name is taken (and the project dead), how about renaming this one to "node-async-flow"?

If this project were officially published through npmjs then I could kill my hack projects.

**Comment by evshiron** [comment]
I have it published as `@evshiron/node-flow`, and now `nwjs-download` and `nwjs-builder` both should be using it instead of the original GitHub repo. Cheers.

**Comment by stackmagic** [comment]
Alright so I tried this, it doesn't want to hit github anymore but of course our nexus v2 doesn't support scoped packages, that's only supported in v3... When we're gonna get that, idk - For now, I'll just leave it at my current hack and once the infra people have upgraded nexus we'll switch back over to your official packages.

Thanks for your work with nwjs-builder, so far it works perfectly. nw.js should make your stuff the recommended way to package the app.
