### ISSUE TITLE
return value

### ISSUE THREAD

**Issue by stkap** [evshiron/node-flow#3]
Is it possible return value from Flow?
For example:  var x=Flow(function*(cb){ return 'World';});

**Comment by evshiron** [comment]
I am afraid not. Just like usual async functions, you won't be able to retrieve the result immediately, and I think there won't be any possibilities (do correct me if I am wrong). `node-async-flow` is to wrap a Generator, making async calls inside act as if they are synchronized.
Async functions usually return a Promise/Deferred if they must. They are not for immediate return, either, but to provide a consistent API across async tasks. I think Promises will be widely used in the future, but not at the moment. `co` and async/await are built on top of Promises, they are the standards, but require more work to get them rolling. I like the simple callback pattern, which `node-async-flow` is designed for.

**Comment by stkap** [comment]
Thank you for the instant answer. Your small Flow pattern is very concise and nice. Actually for the final steps of rendering task we do not need to come back into the synchronous process. Everything could be finished whenever in the flow with response.end. In the Flow generator function we have possibility invoke by name from the global cache some async helper functions(like readFile in your example) that will return value to the generator flow, so we could continue to process a nested template rendering. Am I wrong? I've never written such async functions so, if you have an example, I would like to get one.

**Comment by evshiron** [comment]
Yep, that should work.
The following code snippet demonstrates how to use `node-async-flow` with `express`:

``` javascript
// Global helper functions?
function getUserInfo(session, callback) {
  return callback(null);
}
function handleError(res, { err, path }) {
  return res.render('error', {
    err, path,
  });
}

app.get('/user', (req, res) => {
  Flow(function*(cb) {

    let err, user;

    // Validate user session. A better practice is to do this in a middleware.
    // If invalid, redirect and stop.
    if(!req.session || !req.session.username) {
      return res.redirect('/login');
    }

    // Do some async calls.
    // For example, get user information from a database.
    [err, user] = yield getUserInfo(req.session, cb.expect(2));

    // Error handling.
    if(err) {
      return handleError(res, {
        err,
        path: req.path,
      });
    }

    // Calls to sync functions have nothing special.
    let meta;
    try {
      meta = JSON.parse(user.meta);
    }
    catch(err) {
      return handleError(res, {
        err,
        path: req.path,
      });
    }

    const { username, nickname } = user;

    // Final render.
    return res.render('user', {
      username, nickname, meta,
    });

  });
});
```

To be aware, `Flow` itself is an async function, any bad practices to async functions apply to `node-async-flow` as well. Also, `node-async-flow` enables returning variables into a large single scope, as a result naming conflicts will appear as your application grows.
I have many node.js projects and if there is `node-async-flow` or `evshiron/node-flow` as a dependency in `package.json`, it's used somewhere in the code. Also there are example links in the README of `node-async-flow`.
Feel free to ask if you have further questions :)

**Comment by stkap** [comment]
Thank you. I am really appreciated you for your new example.
I changed it a little bit to be more understandable for me personally:

// Global helper functions example
const Flow = require('node-async-flow');

function getUserInfo(session, callback) {let value='John'; return callback(value); }
function getSomeUserInfo(session, callback) {let value='Sam'; return callback(45,value); }

  Flow(function*(cb) {
    let err, user;

// Do some async calls. For example, get user information from a database.
    user = yield getUserInfo(12, cb.single); 
    console.log('user: '+user);       //John

```
[err, user] = yield getSomeUserInfo(12, cb.expect(2));
console.log('error: '+err);        //45
console.log('user: '+user);      //Sam
```

  });

Don't know why it change text style.

**Comment by evshiron** [comment]
@stkap GitHub use GitHub Flavored Markdown to enable developers formatting their contents on the website, and the 4 spaces indicate the beginning of a code block (looks like it's not a recommended way now).
See also: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
